name: Bug Report
description: Report a bug or unexpected behavior in RazorConsole
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us investigate and fix the issue.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what went wrong...
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create a component with '...'
        2. Run the application with '...'
        3. Observe the error '...'
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what should have happened...
    validations:
      required: true
  
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Information about your environment. 
        You can get detailed CLI info by running the RazorConsole Gallery app and navigating to the "CLI Info" page, which shows OS, .NET version, terminal capabilities, and more.
      placeholder: |
        Run `dotnet run --project src/RazorConsole.Gallery` and navigate to "CLI Info" page to get detailed environment info, or manually provide:
        - RazorConsole version:
        - .NET version:
        - OS:
        - Terminal:
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or code snippets about the problem.
      placeholder: Any additional information that might help...
    validations:
      required: false
