import React from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import rehypeSlug from "rehype-slug"
import CodeBlock from "./CodeBlock"
import type { BundledLanguage } from "shiki"
import { Info, Lightbulb, OctagonAlert, TriangleAlert, Zap } from "lucide-react"

interface MarkdownRendererProps {
  content: string
  className?: string
}

const remarkPluginsList = [remarkGfm]
const rehypePluginsList = [rehypeSlug]

const ALERT_CONFIG: Record<
  string,
  {
    icon: React.ElementType
    title: string
    classes: string
    iconColor: string
  }
> = {
  NOTE: {
    icon: Info,
    title: "Note",
    classes: "bg-blue-50 dark:bg-blue-900/20 border-blue-500 text-blue-800 dark:text-blue-200",
    iconColor: "text-blue-500",
  },
  TIP: {
    icon: Lightbulb,
    title: "Tip",
    classes: "bg-green-50 dark:bg-green-900/20 border-green-500 text-green-800 dark:text-green-200",
    iconColor: "text-green-500",
  },
  IMPORTANT: {
    icon: Zap,
    title: "Important",
    classes:
      "bg-purple-50 dark:bg-purple-900/20 border-purple-500 text-purple-800 dark:text-purple-200",
    iconColor: "text-purple-500",
  },
  WARNING: {
    icon: TriangleAlert,
    title: "Warning",
    classes:
      "bg-yellow-50 dark:bg-yellow-900/20 border-yellow-500 text-yellow-800 dark:text-yellow-200",
    iconColor: "text-yellow-500",
  },
  CAUTION: {
    icon: OctagonAlert,
    title: "Caution",
    classes: "bg-red-50 dark:bg-red-900/20 border-red-500 text-red-800 dark:text-red-200",
    iconColor: "text-red-500",
  },
}
export const MarkdownRenderer = React.memo<MarkdownRendererProps>(({ content, className = "" }) => {
  return (
    <div className={`markdown-renderer ${className}`}>
      <ReactMarkdown
        remarkPlugins={remarkPluginsList}
        rehypePlugins={rehypePluginsList}
        components={{
          // Customize code blocks
          code: ({ className, children, ...props }: any) => {
            const match = /language-(\w+)/.exec(className || "")
            const language = match ? (match[1] as BundledLanguage) : undefined
            const inline = !className?.includes("language-")
            const codeContent = String(children).replace(/\n$/, "")

            if (inline || !match) {
              return (
                <code
                  className="rounded bg-gray-100 px-1 py-0.5 font-mono text-sm text-gray-800 dark:bg-gray-800 dark:text-gray-200"
                  {...props}
                >
                  {children}
                </code>
              )
            }

            return <CodeBlock code={codeContent} language={language} showCopy={true} />
          },

          // Customize tables
          table: ({ children }) => (
            <div className="my-4 overflow-x-auto">
              <table className="min-w-full border-collapse border border-gray-300 dark:border-gray-600">
                {children}
              </table>
            </div>
          ),

          th: ({ children }) => (
            <th className="border border-gray-300 bg-gray-50 px-4 py-2 text-left font-semibold dark:border-gray-600 dark:bg-gray-800">
              {children}
            </th>
          ),

          td: ({ children }) => (
            <td className="border border-gray-300 px-4 py-2 dark:border-gray-600">{children}</td>
          ),

          // Customize headings - spread props to pass ID generated by rehype-slug
          h1: ({ children, ...props }) => (
            <h1
              className="mt-6 mb-4 border-b border-gray-200 pb-2 text-2xl font-bold first:mt-0 dark:border-gray-700"
              {...props}
            >
              {children}
            </h1>
          ),

          h2: ({ children, ...props }) => (
            <h2 className="mt-5 mb-3 text-xl font-bold first:mt-0" {...props}>
              {children}
            </h2>
          ),

          h3: ({ children, ...props }) => (
            <h3 className="mt-4 mb-2 text-lg font-bold first:mt-0" {...props}>
              {children}
            </h3>
          ),

          h4: ({ children, ...props }) => (
            <h4 className="mt-3 mb-2 text-base font-bold first:mt-0" {...props}>
              {children}
            </h4>
          ),

          // Customize paragraphs
          p: ({ children }) => <p className="mb-4 leading-relaxed last:mb-0">{children}</p>,

          // Customize lists
          ul: ({ children }) => (
            <ul className="mb-4 list-inside list-disc space-y-1">{children}</ul>
          ),

          ol: ({ children }) => (
            <ol className="mb-4 list-inside list-decimal space-y-1">{children}</ol>
          ),

          li: ({ children }) => <li className="leading-relaxed">{children}</li>,

          // CUSTOM BLOCKQUOTE WITH ALERTS SUPPORT
          blockquote: ({ children, ...props }) => {
            const childArray = React.Children.toArray(children)

            const firstElementIndex = childArray.findIndex((child) => React.isValidElement(child))
            const firstElement = childArray[firstElementIndex] as React.ReactElement

            if (firstElement) {
              const elementProps = firstElement.props as any
              const pChildren = React.Children.toArray(elementProps.children)
              const firstText = pChildren[0]

              if (typeof firstText === "string") {
                const match = firstText.match(/^\s*\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]/i)

                if (match) {
                  const type = match[1].toUpperCase()
                  const config = ALERT_CONFIG[type] || ALERT_CONFIG.NOTE
                  const Icon = config.icon

                  const newText = firstText.replace(/^\s*\[!.*?\]\s?/, "")

                  const newPChildren = [newText, ...pChildren.slice(1)]

                  const newFirstElement = React.cloneElement(firstElement, {}, newPChildren)

                  const remainingChildren = childArray.slice(firstElementIndex + 1)

                  return (
                    <div className={`my-4 rounded-md border-l-4 p-4 ${config.classes}`}>
                      <div className="mb-2 flex items-center gap-2 font-semibold">
                        <Icon className={`h-5 w-5 ${config.iconColor}`} />
                        <span>{config.title}</span>
                      </div>
                      <div className="text-sm opacity-90 [&>p]:mb-2 [&>p:last-child]:mb-0">
                        {newFirstElement}
                        {remainingChildren}
                      </div>
                    </div>
                  )
                }
              }
            }

            return (
              <blockquote
                className="my-4 border-l-4 border-gray-300 pl-4 text-gray-700 italic dark:border-gray-600 dark:text-gray-300"
                {...props}
              >
                {children}
              </blockquote>
            )
          },
          // Customize links
          a: ({ href, children }) => (
            <a
              href={href}
              className="text-blue-600 underline hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300"
              target="_blank"
              rel="noopener noreferrer"
            >
              {children}
            </a>
          ),

          // Customize horizontal rules
          hr: () => <hr className="my-6 border-gray-300 dark:border-gray-600" />,
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  )
})
